version: 2.1

jobs:
  test:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run: lein test
  lint:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run: lein cljfmt check

workflows:
  test-lint:
    jobs:
      - test
      - lint
